// <auto-generated />
using System;
using Chido.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chido.Data.Migrations
{
    [DbContext(typeof(ChidoDbContext))]
    [Migration("20260730042523_DropBattleSessionMessageId")]
    partial class DropBattleSessionMessageId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Chido.Data.Entities.BattleEffectRecord", b =>
                {
                    b.Property<byte[]>("InstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("instance_id")
                        .HasComment("使い捨てGuid。1回の付与ごとに新規発行");

                    b.Property<byte>("AffectReason")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("affect_reason")
                        .HasComment("付与要因（0: skill, 1: auto）");

                    b.Property<string>("EffectKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("effect_key")
                        .HasComment("chido_effect_master.effect_key を参照");

                    b.Property<byte[]>("EntityId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("entity_id")
                        .HasComment("chido_battle_participant.entity_id を参照。効果保持者（Player/Enemy両方あり得る）");

                    b.Property<string>("GrantSourceKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("grant_source_key")
                        .HasComment("識別キー。skill付与時は skill_key。auto付与時は NULL。affect_reason は本列が「何のキーであるか」を示す型タグであり、本列からは導出できない");

                    b.Property<byte[]>("GranterEntityId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("granter_entity_id")
                        .HasComment("付与者のentity_id。auto付与時は entity_id と同値（自己付与）");

                    b.Property<ushort?>("RemainingActions")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("remaining_actions")
                        .HasComment("残り有効行動数。付与元（10c または 14番）の duration_actions を複製して初期化する。保持者が1ターンに関与するごとに -1 し 0 で消失。NULL=無期限（SQLのNULL伝播により減衰・消失判定から自動的に外れる）");

                    b.HasKey("InstanceId");

                    b.ToTable("chido_battle_effect", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.BattleEnemyEquipmentRecord", b =>
                {
                    b.Property<byte[]>("InstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("instance_id")
                        .HasComment("使い捨てGuid。敵の出現(spawn)時、chido_enemy_equipment_master の抽選結果に基づき新規発行される");

                    b.Property<byte[]>("EnemyId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("enemy_id")
                        .HasComment("chido_battle_enemy.enemy_id を参照");

                    b.Property<string>("EquipKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("equip_key")
                        .HasComment("chido_equipment_master.equip_key を参照");

                    b.HasKey("InstanceId");

                    b.HasIndex("EnemyId")
                        .HasDatabaseName("idx_enemy");

                    b.ToTable("chido_battle_enemy_equipment", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.BattleEnemyEquipmentSlotRecord", b =>
                {
                    b.Property<byte[]>("EnemyId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("enemy_id")
                        .HasComment("chido_battle_enemy.enemy_id を参照");

                    b.Property<byte[]>("Accessory1InstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("accessory1_instance_id")
                        .HasComment("アクセサリスロット1");

                    b.Property<byte[]>("ChestInstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("chest_instance_id")
                        .HasComment("胴防具スロット");

                    b.Property<byte[]>("HeadInstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("head_instance_id")
                        .HasComment("頭防具スロット");

                    b.Property<byte[]>("LegsInstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("legs_instance_id")
                        .HasComment("脚防具スロット");

                    b.Property<byte[]>("WeaponInstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("weapon_instance_id")
                        .HasComment("chido_battle_enemy_equipment.instance_id を参照");

                    b.HasKey("EnemyId");

                    b.ToTable("chido_battle_enemy_equipment_slot", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.BattleEnemyRecord", b =>
                {
                    b.Property<byte[]>("EnemyId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("enemy_id")
                        .HasComment("出現の都度新規発行される使い捨てGuid。1つのenemy_idにつきchido_battle_participant行は常に1つのみ");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("level")
                        .HasComment("敵のレベル。出現時の chido_channel_state.cumulative_enemy_level をそのまま複製する。組の全メンバーが同一レベルとなる。10進整数文字列（BigIntegerToStringConverter 参照）");

                    b.Property<string>("MasterKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("master_key")
                        .HasComment("chido_enemy_master.enemy_key を参照。どの敵か（種別）を示す");

                    b.HasKey("EnemyId");

                    b.HasIndex("MasterKey")
                        .HasDatabaseName("idx_master_key");

                    b.ToTable("chido_battle_enemy", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.BattleLogRecord", b =>
                {
                    b.Property<ulong>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("log_id")
                        .HasComment("ログの連番ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("LogId"));

                    b.Property<byte>("ActionType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("action_type")
                        .HasComment("ActionType（Attack/Skill/Use/Defend/Escape）");

                    b.Property<byte[]>("ActorId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("actor_id")
                        .HasComment("行動主体のentity_id。SlipDamage による継続ダメージでは、被害者ではなく chido_battle_effect.granter_entity_id（付与者）を記録する");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(3)")
                        .HasColumnName("created_at")
                        .HasComment("ログ発生時刻");

                    b.Property<string>("Payload")
                        .HasColumnType("JSON")
                        .HasColumnName("payload")
                        .HasComment("ダメージ量等の詳細（DamageResult等をシリアライズ）。記録するダメージ値は実効ダメージ ＝ min(最終ダメージ, 適用直前の現在HP)");

                    b.Property<byte[]>("SessionId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("session_id")
                        .HasComment("chido_battle_session.session_id を参照");

                    b.Property<byte[]>("TargetId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("target_id")
                        .HasComment("対象のentity_id（対象がいない行動ではNULL）");

                    b.HasKey("LogId");

                    b.HasIndex("SessionId", "LogId")
                        .HasDatabaseName("idx_session_log");

                    b.ToTable("chido_battle_log", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.BattleParticipantRecord", b =>
                {
                    b.Property<byte[]>("SessionId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("session_id")
                        .HasComment("chido_battle_session.session_id を参照");

                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("entity_id")
                        .HasComment("参加者インスタンスの使い捨てGuid（IEntity.Id）");

                    b.Property<string>("CurrentHp")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("current_hp")
                        .HasComment("戦闘中の現在HP。現在HPの唯一の真値。参加時は MaxLife（全快）で初期化される。MaxLife を超える値を取りうる（クランプしない）。「戦闘不能」の判定には使用しない（status 列が唯一の根拠）");

                    b.Property<byte[]>("CurrentTargetId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("current_target_id")
                        .HasComment("現在の攻撃対象。同一session内の他行のentity_idを参照。解決は初回既定・自動失効後の再選定を区別しない単一の導出関数で行い、結果を本列へ書き戻す。Enemy では常にNULL");

                    b.Property<ushort>("CurrentTp")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("current_tp")
                        .HasComment("現在のTP（0〜1000）。Player: 参加時0／Enemy: 出現時 chido_enemy_master.initial_tp で初期化。蓄積量と上限はC#側の定数として保持する");

                    b.Property<ushort>("DisplayOrder")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("display_order")
                        .HasComment("表示順。entity_type ごとに独立した番号空間を持つ。Enemy: spawn_index（＝組の member_index）の恒等複製でターゲット自動再選定の根拠。Player: 参加順（MAX+1 採番）で表示にのみ使用");

                    b.Property<byte[]>("EnemyId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("enemy_id")
                        .HasComment("entity_type=1 のとき必須。chido_battle_enemy.enemy_id を参照");

                    b.Property<byte>("EntityType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("entity_type")
                        .HasComment("0: Player, 1: Enemy");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("DATETIME(3)")
                        .HasColumnName("joined_at")
                        .HasComment("参加時刻の記録。順序付けには使用しない（display_order がその責務を持つ）");

                    b.Property<byte>("RotationIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("rotation_index")
                        .HasComment("敵のローテーション（action_pattern_type=2）の現在位置。出現時0で初期化。選択の成否に関わらず (rotation_index + 1) % total で進める。Player およびローテ以外の敵では未使用");

                    b.Property<byte>("Status")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("status")
                        .HasComment("ParticipantStatus（0: Active, 1: Escaped, 2: Defeated）。current_hp=0 からの間接判定ではなく状態そのものを一次情報として保持する。entity_type を問わず全行に適用される");

                    b.Property<string>("TotalDamageDealt")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("total_damage_dealt")
                        .HasComment("敵参加者へ与えた実効ダメージの累計（台帳）。実効ダメージ = min(最終ダメージ, 適用直前の現在HP)。経験値按分の分子・報酬付与ゲート・分母の集計元となる共通の基準量。SlipDamage は付与者側に計上する");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("entity_type=0 のとき必須。chido_player.user_id を参照");

                    b.HasKey("SessionId", "EntityId");

                    b.HasIndex("SessionId", "EntityType", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("uk_display_order");

                    b.ToTable("chido_battle_participant", null, t =>
                        {
                            t.HasCheckConstraint("CK_chido_battle_participant_entity_type", "(entity_type = 0 AND user_id IS NOT NULL AND enemy_id IS NULL) OR (entity_type = 1 AND user_id IS NULL AND enemy_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Chido.Data.Entities.BattleSessionRecord", b =>
                {
                    b.Property<byte[]>("SessionId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("session_id")
                        .HasComment("使い捨てGuid。プレイヤーの最初の戦闘行為時に新規発行される");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("channel_id")
                        .HasComment("戦闘が発生したチャンネルID。chido_channel_state.channel_id を参照");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(3)")
                        .HasColumnName("created_at")
                        .HasComment("セッション開始時刻");

                    b.Property<byte?>("EndReason")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("end_reason")
                        .HasComment("終了理由。ended_atがNULLの間は常にNULL。BattleEndReason（0: PlayerVictory, 1: PlayerEscaped, 2: EnemyEscaped, 3: ChannelMissing）");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("DATETIME(3)")
                        .HasColumnName("ended_at")
                        .HasComment("終了時刻。NULL=進行中、NOT NULL=終了（phase列の代わりにこれで進行状態を表現する）");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("guild_id")
                        .HasComment("戦闘が発生したDiscordサーバーID");

                    b.HasKey("SessionId");

                    b.ToTable("chido_battle_session", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.BattleStatusRecord", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("chido_player.user_id を参照");

                    b.Property<string>("Exp")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("exp")
                        .HasComment("経験値。レベルは √exp で算出。初期値は 1（0 だと level=0 となり全ステータスが0になって成立しない）。10進整数文字列。ランキングは exp_len との複合インデックスで数値順を得る（DECIMAL が使えない理由は BigIntegerToStringConverter 参照）")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Exp"), "ascii");

                    b.Property<byte>("ExpLength")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("exp_len")
                        .HasComputedColumnSql("CHAR_LENGTH(`exp`)", true)
                        .HasComment("exp の桁数。非負の正準10進文字列では (桁数, 辞書順) が数値順に一致するため、ランキングの第1ソートキーになる。DBが算出する生成列");

                    b.HasKey("UserId");

                    b.HasIndex("ExpLength", "Exp")
                        .HasDatabaseName("idx_exp_rank");

                    b.ToTable("chido_battle_status", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.ChannelCurrentEnemyRecord", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("channel_id")
                        .HasComment("chido_channel_state.channel_id を参照");

                    b.Property<byte>("SpawnIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("spawn_index")
                        .HasComment("組内の出現順。chido_enemy_group_member_master.member_index を引き継ぐ");

                    b.Property<byte[]>("EnemyId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("enemy_id")
                        .HasComment("chido_battle_enemy.enemy_id を参照。書き込みは常に新規インスタンスであり「前のインスタンスを引き継ぐ」経路は存在しない");

                    b.HasKey("ChannelId", "SpawnIndex");

                    b.ToTable("chido_channel_current_enemy", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.ChannelStateRecord", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("channel_id")
                        .HasComment("DiscordチャンネルID。行の存在自体が「このチャンネルは戦闘チャンネルである」ことを意味する。常に行が存在するため、チャンネルに関する悲観ロックのアンカーとして使用する");

                    b.Property<string>("CumulativeEnemyLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("cumulative_enemy_level")
                        .HasComment("累積敵レベル。初期値 1。敵の組を撃破するたびに +1（減少しない）。出現する敵の level にそのまま複製される。2500 の倍数に達するたびにフィールドが切り替わる（専用カウンターは持たない）。10進整数文字列（BigIntegerToStringConverter 参照）");

                    b.Property<string>("CurrentFieldKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("current_field_key")
                        .HasComment("chido_field_master.field_key を参照。現在のフィールド");

                    b.Property<byte[]>("CurrentSessionId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("current_session_id")
                        .HasComment("chido_battle_session.session_id を参照。NULL=進行中のセッションなし。1チャンネル1行という構造により「アクティブなセッションは1つ以下」が導かれ、セッション生成レースを本行のロックで直列化できる");

                    b.HasKey("ChannelId");

                    b.ToTable("chido_channel_state", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EffectDisableMoveMasterRecord", b =>
                {
                    b.Property<string>("EffectKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("effect_key")
                        .HasComment("chido_effect_master.effect_key を参照");

                    b.Property<int>("DisableRate")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("disable_rate")
                        .HasComment("行動不能率。permyriad（0〜10000）。付与時に固定せず、保持者が行動しようとするたびに引く確率。併存する複数インスタンスは instance_id 昇順に独立抽選し最初の成功で打ち切る");

                    b.HasKey("EffectKey");

                    b.ToTable("chido_effect_disable_move_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EffectElementGrantMasterRecord", b =>
                {
                    b.Property<string>("EffectKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("effect_key")
                        .HasComment("chido_effect_master.effect_key を参照");

                    b.Property<uint>("Elements")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("elements")
                        .HasComment("付与する属性（ビット列）。ダメージ計算時、対象の実効属性は「本体属性 ∪ 装備属性 ∪ 一時付与属性」として集計される");

                    b.HasKey("EffectKey");

                    b.ToTable("chido_effect_element_grant_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EffectMasterRecord", b =>
                {
                    b.Property<string>("EffectKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("effect_key")
                        .HasComment("可読キー。10c / 10d / chido_enemy_effects_master から参照される");

                    b.Property<byte>("ClearOnBattleEnd")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("clear_on_battle_end")
                        .HasComment("戦闘終了時に解除するか（0/1）。Player: 1のとき chido_battle_effect／0のとき chido_player_effect。Enemy: 値に関わらず常に chido_battle_effect");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("description")
                        .HasComment("説明文");

                    b.Property<uint>("EffectTypes")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("effect_types")
                        .HasComment("保有効果種別（ビット列）。StatusModifier / SlipDamage / DisableMove / ElementGrant。各サブテーブルの行の有無に対応する非正規化キャッシュであり、真実の情報源はサブテーブル側");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name")
                        .HasComment("表示名");

                    b.HasKey("EffectKey");

                    b.ToTable("chido_effect_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EffectSlipDamageInstanceRecord", b =>
                {
                    b.Property<byte[]>("InstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("instance_id")
                        .HasComment("chido_battle_effect.instance_id または chido_player_effect.instance_id を参照");

                    b.Property<byte>("AttackType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("attack_type")
                        .HasComment("Physical/Magical。付与モーション（10c）または auto 付与（14番）から複製した静的な性質。ダメージ計算時に対象の物理/魔法DEFのどちらを引くかを決めるために保持し続ける");

                    b.Property<string>("StatusAttackValue")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("status_attack_value")
                        .HasComment("付与時点の攻撃力実値のスナップショット。attack_type が指す側の付与者ATK（付与時の StatusModifier 込み）を格納する");

                    b.HasKey("InstanceId");

                    b.ToTable("chido_effect_slip_damage_instance", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EffectSlipDamageMasterRecord", b =>
                {
                    b.Property<string>("EffectKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("effect_key")
                        .HasComment("chido_effect_master.effect_key を参照");

                    b.Property<uint>("Elements")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("elements")
                        .HasComment("攻撃属性（ビット列）。マスタ由来のため付与後も不変であり、スナップショット対象ではない");

                    b.Property<ushort>("Power")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("power")
                        .HasComment("威力。整数%。非負。chido_skill_motion_attack_master.power と同一の概念・同一のスケール");

                    b.HasKey("EffectKey");

                    b.ToTable("chido_effect_slip_damage_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EffectStatusModifierInstanceRecord", b =>
                {
                    b.Property<byte[]>("InstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("instance_id")
                        .HasComment("chido_battle_effect.instance_id または chido_player_effect.instance_id を参照。親が2テーブルに分かれるため FOREIGN KEY は張れない");

                    b.Property<byte>("TargetStatus")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("target_status")
                        .HasComment("chido_effect_status_modifier_master.target_status に対応");

                    b.Property<int>("Rate")
                        .HasColumnType("INT")
                        .HasColumnName("rate")
                        .HasComment("実際の変動率。permyriad、符号あり。マスタの fixed_rate が NULL の行のみここに実値を持つ。値の出所は 10c または 14番の effect_rate");

                    b.HasKey("InstanceId", "TargetStatus");

                    b.ToTable("chido_effect_status_modifier_instance", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EffectStatusModifierMasterRecord", b =>
                {
                    b.Property<string>("EffectKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("effect_key")
                        .HasComment("chido_effect_master.effect_key を参照");

                    b.Property<byte>("TargetStatus")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("target_status")
                        .HasComment("対象ステータス。DRR（ダメージ軽減率）も本列の一値として編入する。HP/攻撃/防御を指す行は (1 + Σr) として乗算レイヤーに入るが、DRR を指す行は Σr を (10000 - Σr)/10000 の形で PostDefense に供給する（合成の意味が異なる。アプリ側で分岐）");

                    b.Property<int?>("FixedRate")
                        .HasColumnType("INT")
                        .HasColumnName("fixed_rate")
                        .HasComment("固定変動率。permyriad、符号あり。NOT NULL=マスタ定義の固定値（防御 Defend の DRR 50% → 5000）／NULL=不定値（適用時にインスタンス側が変動率を保持する）");

                    b.HasKey("EffectKey", "TargetStatus");

                    b.ToTable("chido_effect_status_modifier_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EnemyCurrencyMasterRecord", b =>
                {
                    b.Property<string>("EnemyKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("enemy_key")
                        .HasComment("chido_enemy_master.enemy_key を参照");

                    b.Property<string>("DropAmount")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("drop_amount")
                        .HasComment("撃破時に確定でドロップする金額（固定値、抽選なし）。10進整数文字列（BigIntegerToStringConverter 参照）");

                    b.HasKey("EnemyKey");

                    b.ToTable("chido_enemy_currency_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EnemyEffectsMasterRecord", b =>
                {
                    b.Property<string>("EnemyKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("enemy_key")
                        .HasComment("chido_enemy_master.enemy_key を参照");

                    b.Property<byte>("EnemyEffectIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("enemy_effect_index")
                        .HasComment("付与順序");

                    b.Property<byte?>("AttackType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("attack_type")
                        .HasComment("Physical/Magical。付与する状態変化が SlipDamage 成分を持つ場合のみ NOT NULL。auto 付与の SlipDamage（「6行動で自滅する敵」等）が物理/魔法を決めるために必要");

                    b.Property<ushort?>("DurationActions")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("duration_actions")
                        .HasComment("持続。「残り有効行動数」であり時計ではない。NULL=無期限（敵の効果は clear_on_battle_end によらず戦闘終了時に除去される）。0 は取らない");

                    b.Property<string>("EffectKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("effect_key")
                        .HasComment("chido_effect_master.effect_key を参照");

                    b.Property<int>("EffectRate")
                        .HasColumnType("INT")
                        .HasColumnName("effect_rate")
                        .HasComment("効果量。permyriad、符号あり（デバフの負値を許容）。chido_skill_motion_effect_master.effect_rate と同じ性質・同じ書き込み先");

                    b.Property<int>("GrantRate")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("grant_rate")
                        .HasComment("付与確率。permyriad（10000 = 100%）");

                    b.HasKey("EnemyKey", "EnemyEffectIndex");

                    b.HasIndex("EnemyKey", "EffectKey")
                        .IsUnique()
                        .HasDatabaseName("uk_enemy_effect");

                    b.ToTable("chido_enemy_effects_master", null, t =>
                        {
                            t.HasCheckConstraint("CK_chido_enemy_effects_master_duration", "duration_actions IS NULL OR duration_actions >= 1");
                        });
                });

            modelBuilder.Entity("Chido.Data.Entities.EnemyEquipmentMasterRecord", b =>
                {
                    b.Property<string>("EnemyKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("enemy_key")
                        .HasComment("chido_enemy_master.enemy_key を参照");

                    b.Property<byte>("EnemyEquipmentIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("enemy_equipment_index")
                        .HasComment("抽選候補の連番");

                    b.Property<int>("DropRate")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("drop_rate")
                        .HasComment("ドロップ率。permyriad。equip_rate とは独立した確率値");

                    b.Property<string>("EquipKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("equip_key")
                        .HasComment("chido_equipment_master.equip_key を参照");

                    b.Property<int>("EquipRate")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("equip_rate")
                        .HasComment("装着確率。permyriad。同一スロット内の候補の合計が 10000 未満の場合、残差は「そのスロットに装備なし」を選ぶ暗黙の重みとして扱う。超えた場合は相対比率のみの重み付き抽選へフォールバック（アプリ側の責務）");

                    b.HasKey("EnemyKey", "EnemyEquipmentIndex");

                    b.ToTable("chido_enemy_equipment_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EnemyGroupMasterRecord", b =>
                {
                    b.Property<string>("GroupKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("group_key")
                        .HasComment("可読キー（例: 'slime_x3'）");

                    b.Property<byte>("Rarity")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("rarity")
                        .HasComment("組のレアリティ。敵の出現抽選およびEscape時の再抽選例外の判定は、個体ではなく組のレアリティで行う");

                    b.HasKey("GroupKey");

                    b.ToTable("chido_enemy_group_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EnemyGroupMemberMasterRecord", b =>
                {
                    b.Property<string>("GroupKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("group_key")
                        .HasComment("chido_enemy_group_master.group_key を参照");

                    b.Property<byte>("MemberIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("member_index")
                        .HasComment("出現順。chido_channel_current_enemy.spawn_index に引き継がれ、表示順とターゲット自動再選定における「先頭の敵」を決定する");

                    b.Property<string>("EnemyKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("enemy_key")
                        .HasComment("chido_enemy_master.enemy_key を参照");

                    b.HasKey("GroupKey", "MemberIndex");

                    b.ToTable("chido_enemy_group_member_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EnemyLootsMasterRecord", b =>
                {
                    b.Property<string>("EnemyKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("enemy_key")
                        .HasComment("chido_enemy_master.enemy_key を参照");

                    b.Property<string>("ItemKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("item_key")
                        .HasComment("chido_item_master.item_key を参照");

                    b.Property<int>("DropRate")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("drop_rate")
                        .HasComment("ドロップ率。permyriad（10000 = 100%）。判定は撃破に関与したプレイヤーごとに独立して行われる");

                    b.Property<ushort>("Quantity")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("quantity")
                        .HasComment("ドロップ数量");

                    b.HasKey("EnemyKey", "ItemKey");

                    b.ToTable("chido_enemy_loots_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EnemyMasterRecord", b =>
                {
                    b.Property<string>("EnemyKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("enemy_key")
                        .HasComment("可読キー。chido_battle_enemy.master_key から参照される");

                    b.Property<byte>("ActionPatternType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("action_pattern_type")
                        .HasComment("行動パターン（0: 完全ランダム, 1: 重み付きランダム, 2: ローテーション）。スキルの選択規則");

                    b.Property<byte>("AllyTargetRule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("ally_target_rule")
                        .HasComment("味方対象モーションの対象選択規則（種族単位）。番号は族ごとに範囲を予約する（ランダム系 0-9 / 固定対象系 10-19 / 情報参照系 20-29）。現行実装は 0 / 1 / 24 の3規則のみ");

                    b.Property<uint>("Elements")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("elements")
                        .HasComment("敵本体の属性（ビット列）。0 = 属性なし。実効属性は「本体属性 ∪ 装備属性 ∪ 一時付与属性」で算出される。プレイヤーの本体属性は常に 0 のため対応列を持たない");

                    b.Property<int>("ExpRate")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("exp_rate")
                        .HasComment("経験値倍率。permyriad（10000=等倍）。strength_rate とは独立した値");

                    b.Property<ushort>("HpShape")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("hp_shape")
                        .HasComment("HP Shape（種族値に相当する正規化されたステータス倍率）。1.00 を 100 として格納（permyriad ではない）。基礎ステータス = レベル × Scale（HP:12 / 攻撃・防御:8） × Shape");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("image_url")
                        .HasComment("敵画像URL。Discord埋め込みに使用");

                    b.Property<ushort>("InitialTp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("initial_tp")
                        .HasComment("出現時の初期TP（0〜1000）。chido_battle_participant.current_tp の初期値。プレイヤーは常に0で初期化されるためこの非対称は意図的");

                    b.Property<ushort>("MAtkShape")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("matk_shape")
                        .HasComment("魔法攻撃力 Shape（100=等倍）");

                    b.Property<ushort>("MDefShape")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("mdef_shape")
                        .HasComment("魔法防御力 Shape（100=等倍）");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name")
                        .HasComment("表示名");

                    b.Property<ushort>("PAtkShape")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("patk_shape")
                        .HasComment("物理攻撃力 Shape（100=等倍）");

                    b.Property<ushort>("PDefShape")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("pdef_shape")
                        .HasComment("物理防御力 Shape（100=等倍）");

                    b.Property<byte>("Rarity")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("rarity")
                        .HasComment("レアリティ（0: Common, 1: Uncommon, 2: Rare, 3: Mythic, 4: Hidden）。個体の希少度を示す表示専用の値であり、敵の出現抽選には使用しない（抽選は chido_enemy_group_master.rarity）");

                    b.Property<ushort>("Speed")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("speed")
                        .HasComment("素早さ。Scale × Shape の枠組みには含まれない固定値（プレイヤーは基本500）。変動要因は装備効果のみ");

                    b.Property<int>("StrengthRate")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("strength_rate")
                        .HasComment("強さ倍率。permyriad（10000=等倍）。戦闘時ステータス = 基礎ステータス × 強さ倍率 × 装備補正 × 状態変化補正。プレイヤーは常に等倍");

                    b.HasKey("EnemyKey");

                    b.ToTable("chido_enemy_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EnemySkillsMasterRecord", b =>
                {
                    b.Property<string>("EnemyKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("enemy_key")
                        .HasComment("chido_enemy_master.enemy_key を参照");

                    b.Property<byte>("EnemySkillIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("enemy_skill_index")
                        .HasComment("再生・抽選順序。ローテーションの total は本テーブルの登録行数");

                    b.Property<string>("SkillKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("skill_key")
                        .HasComment("chido_skill_master.skill_key を参照");

                    b.Property<byte>("Weight")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("weight")
                        .HasComment("抽選の相対重み。合計値に意味を持たず Ratio への変換対象外。action_pattern_type=1 でのみ参照される。0=抽選対象外だが、完全ランダム／ローテーションでは本列自体が無視されるため通常通り使用される（意図的な非対称）");

                    b.HasKey("EnemyKey", "EnemySkillIndex");

                    b.ToTable("chido_enemy_skills_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.EquipmentMasterRecord", b =>
                {
                    b.Property<string>("EquipKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("equip_key")
                        .HasComment("可読キー");

                    b.Property<uint>("Elements")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("elements")
                        .HasComment("装備が付与する属性（ビット列）。0 = 属性なし。プレイヤーの本体属性は装備由来のみであり、装着中の全スロットの elements の OR で決まる");

                    b.Property<uint>("EquipParts")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("equip_parts")
                        .HasComment("装備可能パーツ（ビット列。weapon/head/chest/legs/accessory）。スロットの種別（候補）を表すものであり物理カラムと1対1対応する保証はない（択一の候補提示を許容する）");

                    b.Property<int>("HpRate")
                        .HasColumnType("INT")
                        .HasColumnName("hp_rate")
                        .HasComment("HP補正値。permyriad、符号あり（10000=等倍、0=このステータスに無効果、負値=デメリット装備）");

                    b.Property<int>("LuckBonusRate")
                        .HasColumnType("INT")
                        .HasColumnName("luck_bonus_rate")
                        .HasComment("運補正値。permyriad、符号あり。乗算ではなく%ポイントの加算（例: +5% → 500）");

                    b.Property<int>("MAtkRate")
                        .HasColumnType("INT")
                        .HasColumnName("matk_rate")
                        .HasComment("魔法攻撃力補正値（同上）");

                    b.Property<int>("MDefRate")
                        .HasColumnType("INT")
                        .HasColumnName("mdef_rate")
                        .HasComment("魔法防御力補正値（同上）");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name")
                        .HasComment("表示名");

                    b.Property<int>("PAtkRate")
                        .HasColumnType("INT")
                        .HasColumnName("patk_rate")
                        .HasComment("物理攻撃力補正値（同上）");

                    b.Property<int>("PDefRate")
                        .HasColumnType("INT")
                        .HasColumnName("pdef_rate")
                        .HasComment("物理防御力補正値（同上）");

                    b.Property<string>("ProgressionValue")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("progression_value")
                        .HasComment("レベルに対する想定進行度 P(level) の結果値のみを格納（例: Lv5000でP(5000)=60）。レアリティ補正(×1.2^rarity)や各ステータス補正の乗算はアプリ側で都度算出する。10進整数文字列（BigIntegerToStringConverter 参照）");

                    b.Property<byte>("Rarity")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("rarity")
                        .HasComment("装備レアリティ（0〜4）。chido_enemy_master.rarity と共通のenum。同一進行度内での強さの序列付けに使用");

                    b.Property<int>("SpeedBonus")
                        .HasColumnType("INT")
                        .HasColumnName("speed_bonus")
                        .HasComment("素早さ固定変動値。絶対値の加減算（例: +50 / -30）。Ratio への変換対象外");

                    b.HasKey("EquipKey");

                    b.ToTable("chido_equipment_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.FieldEnemyGroupMasterRecord", b =>
                {
                    b.Property<string>("FieldKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("field_key")
                        .HasComment("chido_field_master.field_key を参照");

                    b.Property<string>("GroupKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("group_key")
                        .HasComment("chido_enemy_group_master.group_key を参照");

                    b.Property<byte>("Rarity")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("rarity")
                        .HasComment("chido_enemy_group_master.rarity の非正規化キャッシュ。「フィールドF・レアリティRの組」を単一インデックスで引くために複製する。真実の情報源は組マスタ側であり整合性の維持はアプリ側の責務");

                    b.HasKey("FieldKey", "GroupKey");

                    b.HasIndex("FieldKey", "Rarity")
                        .HasDatabaseName("idx_field_rarity");

                    b.ToTable("chido_field_enemy_group_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.FieldMasterRecord", b =>
                {
                    b.Property<string>("FieldKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("field_key")
                        .HasComment("可読キー（例: 'grassland'）");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name")
                        .HasComment("表示名（例: '草原'）");

                    b.HasKey("FieldKey");

                    b.ToTable("chido_field_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.FieldRarityRateMasterRecord", b =>
                {
                    b.Property<string>("FieldKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("field_key")
                        .HasComment("chido_field_master.field_key を参照");

                    b.Property<byte>("Rarity")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("rarity")
                        .HasComment("レアリティ（0: Common, 1: Uncommon, 2: Rare, 3: Mythic）。Hidden(4) はイベント専用であり通常抽選の対象に一切含まれないため、行として存在させない");

                    b.Property<int>("RarityRate")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("rarity_rate")
                        .HasComment("抽選率。permyriad。同一 field_key 内の合計が 10000 になる（残差は存在しない＝必ず1つ選ばれる）");

                    b.HasKey("FieldKey", "Rarity");

                    b.ToTable("chido_field_rarity_rate_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.FieldTransitionMasterRecord", b =>
                {
                    b.Property<string>("FieldKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("field_key")
                        .HasComment("chido_field_master.field_key を参照。遷移元");

                    b.Property<string>("NextFieldKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("next_field_key")
                        .HasComment("chido_field_master.field_key を参照。遷移先候補。移動先は候補リストから完全ランダムで抽選するため重み列を持たない。自己参照行は「そこから動かない」という意図の明示（0件はマスタ不整合とみなし草原へフォールバック）");

                    b.HasKey("FieldKey", "NextFieldKey");

                    b.ToTable("chido_field_transition_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.ItemMasterRecord", b =>
                {
                    b.Property<string>("ItemKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("item_key")
                        .HasComment("可読キー");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("description")
                        .HasComment("説明文");

                    b.Property<byte>("IsConsumable")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("is_consumable")
                        .HasComment("消費アイテムか（0/1）。item_type とは独立したフラグとして持つ");

                    b.Property<byte>("ItemType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("item_type")
                        .HasComment("アイテム種別（0: battle, 1: material, 2: collection, 3: skill_learning）。battle は戦闘ステータスに作用する戦闘用アイテムで Use アクションの対象。skill_learning は chido_item_used_effect_master 側を真実の情報源とする非正規化キャッシュ");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name")
                        .HasComment("表示名");

                    b.Property<string>("SpecialProcessKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("special_process_key")
                        .HasComment("特殊処理呼び出し記号。NULL=標準処理のみで完結。値がある場合、標準処理では説明のつかない専用ロジックがアプリ側に別途存在することを示す");

                    b.HasKey("ItemKey");

                    b.ToTable("chido_item_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.ItemUsedEffectMasterRecord", b =>
                {
                    b.Property<string>("ItemKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("item_key")
                        .HasComment("chido_item_master.item_key を参照");

                    b.Property<byte>("UsageIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("usage_index")
                        .HasComment("効果の連番。use_skill（スキル発動）は常に1件のみ、learn_skill（スキル習得）は複数件を許容");

                    b.Property<byte>("ItemUsageType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("item_usage_type")
                        .HasComment("アイテム効果種別（0: use_skill, 1: learn_skill。今後拡張予定）");

                    b.Property<string>("SkillKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("skill_key")
                        .HasComment("chido_skill_master.skill_key を参照。use_skill/learn_skill で使用。item_usage_type は今後拡張予定のため他の効果種別を見据えてNULL許容としている");

                    b.HasKey("ItemKey", "UsageIndex");

                    b.ToTable("chido_item_used_effect_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.PlayerCurrencyRecord", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("chido_player.user_id を参照");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("amount")
                        .HasComment("所持金額。10進整数文字列。ランキングは amount_len との複合インデックスで数値順を得る（chido_battle_status.exp と同じ判断基準）")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Amount"), "ascii");

                    b.Property<byte>("AmountLength")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("amount_len")
                        .HasComputedColumnSql("CHAR_LENGTH(`amount`)", true)
                        .HasComment("amount の桁数。非負の正準10進文字列では (桁数, 辞書順) が数値順に一致するため、ランキングの第1ソートキーになる。DBが算出する生成列");

                    b.HasKey("UserId");

                    b.HasIndex("AmountLength", "Amount")
                        .HasDatabaseName("idx_amount_rank");

                    b.ToTable("chido_player_currency", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.PlayerEffectRecord", b =>
                {
                    b.Property<byte[]>("InstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("instance_id")
                        .HasComment("使い捨てGuid。1回の付与ごとに新規発行");

                    b.Property<byte>("AffectReason")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("affect_reason")
                        .HasComment("付与要因（0: skill, 1: auto）");

                    b.Property<string>("EffectKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("effect_key")
                        .HasComment("chido_effect_master.effect_key を参照");

                    b.Property<string>("GrantSourceKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("grant_source_key")
                        .HasComment("識別キー。skill付与時は skill_key。auto付与時は NULL");

                    b.Property<byte[]>("GranterEntityId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("granter_entity_id")
                        .HasComment("付与時点における付与者のentity_id（履歴的参照）。重複付与の一意性判定には使用しない（セッションごとの使い捨てGuidのため、判定に含めると常に「重複ではない」となり機能しない）");

                    b.Property<ushort>("RemainingActions")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("remaining_actions")
                        .HasComment("残り有効行動数。保持者が1ターンに関与するごとに -1 し 0 で消滅。戦闘の境界では減衰も消滅もしない。NOT NULL: 永続スコープの効果は必ず有限でなければならない（終わりを保証するものが行動数しかないため）");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("chido_player.user_id を参照。効果保持者（Playerのみ。Enemyは出現の都度使い捨てのため永続効果を持つ意味がない）");

                    b.HasKey("InstanceId");

                    b.ToTable("chido_player_effect", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.PlayerEquipmentRecord", b =>
                {
                    b.Property<byte[]>("InstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("instance_id")
                        .HasComment("使い捨てGuid。装備を入手する都度新規発行される");

                    b.Property<string>("EquipKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("equip_key")
                        .HasComment("chido_equipment_master.equip_key を参照");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("chido_player.user_id を参照。所有者");

                    b.HasKey("InstanceId");

                    b.HasIndex("UserId", "EquipKey")
                        .HasDatabaseName("idx_user_equip");

                    b.ToTable("chido_player_equipment", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.PlayerEquipmentSlotRecord", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("chido_player.user_id を参照");

                    b.Property<byte[]>("Accessory1InstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("accessory1_instance_id")
                        .HasComment("アクセサリスロット1");

                    b.Property<byte[]>("ChestInstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("chest_instance_id")
                        .HasComment("胴防具スロット");

                    b.Property<byte[]>("HeadInstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("head_instance_id")
                        .HasComment("頭防具スロット");

                    b.Property<byte[]>("LegsInstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("legs_instance_id")
                        .HasComment("脚防具スロット");

                    b.Property<byte[]>("WeaponInstanceId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("weapon_instance_id")
                        .HasComment("chido_player_equipment.instance_id を参照。武器スロット");

                    b.HasKey("UserId");

                    b.ToTable("chido_player_equipment_slot", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.PlayerInBattleSessionRecord", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("chido_player.user_id を参照。1プレイヤー1行という構造により「同時参加は1セッションまで」がテーブル構造から導かれる。行の不在＝非戦闘中");

                    b.Property<byte[]>("EntityId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("entity_id")
                        .HasComment("chido_battle_participant.entity_id を参照。(session_id, entity_id) によるPK直引きを可能にするための非正規化");

                    b.Property<byte[]>("SessionId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("session_id")
                        .HasComment("chido_battle_session.session_id を参照");

                    b.HasKey("UserId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_session");

                    b.ToTable("chido_player_in_battle_session", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.PlayerItemRecord", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("chido_player.user_id を参照");

                    b.Property<string>("ItemKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("item_key")
                        .HasComment("chido_item_master.item_key を参照");

                    b.Property<uint>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT UNSIGNED")
                        .HasDefaultValue(0u)
                        .HasColumnName("quantity")
                        .HasComment("所持数");

                    b.HasKey("UserId", "ItemKey");

                    b.ToTable("chido_player_item", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.PlayerRecord", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("Discordユーザーの永続ID（スノーフレーク）。常に行が存在するため、プレイヤーに関する悲観ロックのアンカーとして使用する");

                    b.Property<string>("UserName")
                        .HasColumnType("VARCHAR(72)")
                        .HasColumnName("user_name")
                        .HasComment("表示名のキャッシュ。Discord APIから毎回引くとレイテンシが大きいため保持。将来的にニックネーム機能にも転用可能");

                    b.HasKey("UserId");

                    b.ToTable("chido_player", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.PlayerSkillRecord", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("chido_player.user_id を参照");

                    b.Property<string>("SkillKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("skill_key")
                        .HasComment("chido_skill_master.skill_key を参照。通常攻撃（Attack）と防御（Defend）は習得管理の対象外であり行を持たない");

                    b.Property<byte>("LearnedReason")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("learned_reason")
                        .HasComment("習得理由（0: level, 1: item, 2: cheat）");

                    b.HasKey("UserId", "SkillKey");

                    b.ToTable("chido_player_skill", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.PlayerTitleDisplayRecord", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("chido_player.user_id を参照");

                    b.Property<string>("TitleKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("title_key")
                        .HasComment("chido_player_title.title_key を参照。NULL=称号を表示しない");

                    b.HasKey("UserId");

                    b.ToTable("chido_player_title_display", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.PlayerTitleRecord", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("chido_player.user_id を参照");

                    b.Property<string>("TitleKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("title_key")
                        .HasComment("chido_title_master.title_key を参照");

                    b.HasKey("UserId", "TitleKey");

                    b.ToTable("chido_player_title", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.SkillMasterRecord", b =>
                {
                    b.Property<string>("SkillKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("skill_key")
                        .HasComment("可読キー");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("description")
                        .HasComment("説明文");

                    b.Property<uint>("Elements")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("elements")
                        .HasComment("スキル属性（ビット列）。ダメージ計算には一切使用しない、UI表示専用の\"見せかけ\"の値。ダメージ計算が参照するのは chido_skill_motion_attack_master.elements");

                    b.Property<string>("LearnableLevel")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("learnable_level")
                        .HasComment("習得レベル。NULL=レベルアップでは習得不可。10進整数文字列。レベル閾値の判定は C# 側で行う（BigIntegerToStringConverter 参照）");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name")
                        .HasComment("表示名");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0)
                        .HasColumnName("priority")
                        .HasComment("行動優先度。行動順は priority 降順 → Speed → Random。既定は 0（Attack・通常スキル）。Defend には正の値を与え、Speed に関わらず被弾前に構えを取れるようにする");

                    b.Property<ushort>("RequireTp")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("require_tp")
                        .HasComment("TP消費量（0-1000）。回復モーションを含むスキルでは 200 以上とする（運用制約）。166 以下では被反撃だけでTPが自給でき回復威力の実用帯が消滅する");

                    b.Property<string>("SpecialProcessKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("special_process_key")
                        .HasComment("特殊処理呼び出し記号。NULL=標準の効果計算処理のみで完結");

                    b.HasKey("SkillKey");

                    b.ToTable("chido_skill_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.SkillMotionAttackMasterRecord", b =>
                {
                    b.Property<string>("SkillKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("skill_key")
                        .HasComment("chido_skill_motion_master.skill_key を参照（判別子を含む複合FKの構成列）");

                    b.Property<byte>("MotionIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("motion_index")
                        .HasComment("chido_skill_motion_master.motion_index を参照（判別子を含む複合FKの構成列）");

                    b.Property<byte>("AttackType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("attack_type")
                        .HasComment("Physical/Magical。参照する攻撃力を選択する");

                    b.Property<uint>("Elements")
                        .HasColumnType("INT UNSIGNED")
                        .HasColumnName("elements")
                        .HasComment("モーション属性（ビット列）。攻撃モーションのみが持つ。0（属性なし）が意味を持つ既定値（相性計算をスキップ＝全属性等倍）");

                    b.Property<byte>("MotionType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("motion_type")
                        .HasComment("0（攻撃）");

                    b.Property<ushort>("Power")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("power")
                        .HasComment("威力。整数%（通常攻撃=100）。permyriad ではない点に注意。ダメージ = 攻撃力 × 威力 × 被防御係数(ATK÷(ATK+DEF))");

                    b.HasKey("SkillKey", "MotionIndex");

                    b.HasIndex("SkillKey", "MotionIndex", "MotionType")
                        .IsUnique();

                    b.ToTable("chido_skill_motion_attack_master", null, t =>
                        {
                            t.HasCheckConstraint("CK_chido_skill_motion_attack_master_motion_type", "motion_type = 0");
                        });
                });

            modelBuilder.Entity("Chido.Data.Entities.SkillMotionDispelMasterRecord", b =>
                {
                    b.Property<string>("SkillKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("skill_key")
                        .HasComment("chido_skill_motion_master.skill_key を参照（判別子を含む複合FKの構成列）");

                    b.Property<byte>("MotionIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("motion_index")
                        .HasComment("chido_skill_motion_master.motion_index を参照（判別子を含む複合FKの構成列）");

                    b.Property<string>("EffectKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("effect_key")
                        .HasComment("解除対象。対象が保持する全スコープ（chido_battle_effect + chido_player_effect）から effect_key が一致する行をすべて削除する。granter_entity_id / grant_source_key / affect_reason は参照しない");

                    b.Property<byte>("MotionType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("motion_type")
                        .HasComment("4（状態変化解除）");

                    b.HasKey("SkillKey", "MotionIndex");

                    b.HasIndex("EffectKey");

                    b.HasIndex("SkillKey", "MotionIndex", "MotionType")
                        .IsUnique();

                    b.ToTable("chido_skill_motion_dispel_master", null, t =>
                        {
                            t.HasCheckConstraint("CK_chido_skill_motion_dispel_master_motion_type", "motion_type = 4");
                        });
                });

            modelBuilder.Entity("Chido.Data.Entities.SkillMotionEffectMasterRecord", b =>
                {
                    b.Property<string>("SkillKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("skill_key")
                        .HasComment("chido_skill_motion_master.skill_key を参照（判別子を含む複合FKの構成列）");

                    b.Property<byte>("MotionIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("motion_index")
                        .HasComment("chido_skill_motion_master.motion_index を参照（判別子を含む複合FKの構成列）");

                    b.Property<byte?>("AttackType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("attack_type")
                        .HasComment("Physical/Magical。付与する状態変化が SlipDamage 成分を持つ場合に継続ダメージの基準を決める。付与時に chido_effect_slip_damage_instance.attack_type へ複製される。SlipDamage 成分を持たない付与では NULL");

                    b.Property<ushort?>("DurationActions")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("duration_actions")
                        .HasComment("持続。「残り有効行動数」であり時計ではない。remaining_actions の初期値として複製される。NULL=無期限、0 は取らない。付与先 effect の clear_on_battle_end=0 の場合は NOT NULL 必須（アプリ側の責務）");

                    b.Property<string>("EffectKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("effect_key")
                        .HasComment("付与する状態変化。chido_effect_master.effect_key を参照");

                    b.Property<int?>("EffectRate")
                        .HasColumnType("INT")
                        .HasColumnName("effect_rate")
                        .HasComment("効果量。permyriad、符号あり（デバフの負値を許容）。付与先の fixed_rate が NULL の行に対してのみ必須。SlipDamage／DisableMove の効果量はそれぞれのマスタが持つため本列を使用しない");

                    b.Property<byte>("MotionType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("motion_type")
                        .HasComment("2（状態変化付与）");

                    b.HasKey("SkillKey", "MotionIndex");

                    b.HasIndex("EffectKey");

                    b.HasIndex("SkillKey", "MotionIndex", "MotionType")
                        .IsUnique();

                    b.ToTable("chido_skill_motion_effect_master", null, t =>
                        {
                            t.HasCheckConstraint("CK_chido_skill_motion_effect_master_duration", "duration_actions IS NULL OR duration_actions >= 1");

                            t.HasCheckConstraint("CK_chido_skill_motion_effect_master_motion_type", "motion_type = 2");
                        });
                });

            modelBuilder.Entity("Chido.Data.Entities.SkillMotionHealMasterRecord", b =>
                {
                    b.Property<string>("SkillKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("skill_key")
                        .HasComment("chido_skill_motion_master.skill_key を参照（判別子を含む複合FKの構成列）");

                    b.Property<byte>("MotionIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("motion_index")
                        .HasComment("chido_skill_motion_master.motion_index を参照（判別子を含む複合FKの構成列）");

                    b.Property<byte>("AttackType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("attack_type")
                        .HasComment("Physical/Magical。参照する攻撃力を選択する");

                    b.Property<byte>("MotionType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("motion_type")
                        .HasComment("1（回復）");

                    b.Property<ushort>("Power")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("power")
                        .HasComment("威力。整数%。回復量 = 攻撃力 × 威力（対象の防御力は影響しない＝被防御係数1の攻撃）。同格では被防御係数が0.5になるため、通常攻撃(100%)と釣り合う回復は威力50%");

                    b.HasKey("SkillKey", "MotionIndex");

                    b.HasIndex("SkillKey", "MotionIndex", "MotionType")
                        .IsUnique();

                    b.ToTable("chido_skill_motion_heal_master", null, t =>
                        {
                            t.HasCheckConstraint("CK_chido_skill_motion_heal_master_motion_type", "motion_type = 1");
                        });
                });

            modelBuilder.Entity("Chido.Data.Entities.SkillMotionMasterRecord", b =>
                {
                    b.Property<string>("SkillKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("skill_key")
                        .HasComment("chido_skill_master.skill_key を参照");

                    b.Property<byte>("MotionIndex")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("motion_index")
                        .HasComment("再生順序。スキルはこの昇順にモーションを再生する");

                    b.Property<ushort?>("AccuracyGateGroup")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("accuracy_gate_group")
                        .HasComment("命中の依存グループ。NULL=単独で判定。同一 skill_key 内で同値の行が1グループを成し motion_index 最小の行を先頭とする。先頭が効果適用に到達しなければ同一グループの他メンバーは抽選せずスキップ。整合性検証はアプリ側の責務");

                    b.Property<int>("AccuracyRate")
                        .HasColumnType("SMALLINT UNSIGNED")
                        .HasColumnName("accuracy_rate")
                        .HasComment("命中率（攻撃・回復）／成功率（状態変化付与・解除・戦闘離脱）。permyriad。4種すべてが使用する真の共通列であるため親に置く。Attack/Defend は 10000 固定");

                    b.Property<byte>("MotionType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("motion_type")
                        .HasComment("モーション種別。サブタイプの判別子（0: 攻撃→10a, 1: 回復→10b, 2: 状態変化付与→10c, 3: 戦闘離脱→サブタイプなし, 4: 状態変化解除→10d）");

                    b.Property<byte>("TargetRule")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("target_rule")
                        .HasComment("対象の解決規則（0: 自分自身, 1: 味方, 2: 敵）。常に単体固定。敵の味方対象モーションは chido_enemy_master.ally_target_rule で解決する");

                    b.HasKey("SkillKey", "MotionIndex");

                    b.HasAlternateKey("SkillKey", "MotionIndex", "MotionType")
                        .HasName("uk_subtype");

                    b.ToTable("chido_skill_motion_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.TitleMasterRecord", b =>
                {
                    b.Property<string>("TitleKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("title_key")
                        .HasComment("可読キー");

                    b.Property<byte>("AcquisitionType")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("acquisition_type")
                        .HasComment("入手条件種別（0: 特定アイテム獲得, 1: 特定敵撃破, 2: レベル到達, 3: 所持金額到達）。今後拡張予定");

                    b.Property<string>("ConditionKey")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("condition_key")
                        .HasComment("判定値(識別ID形式)。acquisition_type=0→item_key, 1→enemy_key を参照（参照先は acquisition_type により分岐）");

                    b.Property<string>("ConditionValue")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("condition_value")
                        .HasComment("判定値(数値)。acquisition_type=2→レベル閾値、3→所持金額閾値。比較対象（exp由来のレベル、chido_player_currency.amount）と型を揃えている（いずれも VARCHAR(100)。BigIntegerToStringConverter 参照）");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("emoji")
                        .HasComment("表示用絵文字。Unicode文字、またはDiscordカスタム絵文字の完成済みタグ文字列(<:name:id>)をそのまま格納");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name")
                        .HasComment("表示名");

                    b.HasKey("TitleKey");

                    b.ToTable("chido_title_master", (string)null);
                });

            modelBuilder.Entity("Chido.Data.Entities.SkillMotionAttackMasterRecord", b =>
                {
                    b.HasOne("Chido.Data.Entities.SkillMotionMasterRecord", null)
                        .WithOne()
                        .HasForeignKey("Chido.Data.Entities.SkillMotionAttackMasterRecord", "SkillKey", "MotionIndex", "MotionType")
                        .HasPrincipalKey("Chido.Data.Entities.SkillMotionMasterRecord", "SkillKey", "MotionIndex", "MotionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Chido.Data.Entities.SkillMotionDispelMasterRecord", b =>
                {
                    b.HasOne("Chido.Data.Entities.EffectMasterRecord", null)
                        .WithMany()
                        .HasForeignKey("EffectKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chido.Data.Entities.SkillMotionMasterRecord", null)
                        .WithOne()
                        .HasForeignKey("Chido.Data.Entities.SkillMotionDispelMasterRecord", "SkillKey", "MotionIndex", "MotionType")
                        .HasPrincipalKey("Chido.Data.Entities.SkillMotionMasterRecord", "SkillKey", "MotionIndex", "MotionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Chido.Data.Entities.SkillMotionEffectMasterRecord", b =>
                {
                    b.HasOne("Chido.Data.Entities.EffectMasterRecord", null)
                        .WithMany()
                        .HasForeignKey("EffectKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chido.Data.Entities.SkillMotionMasterRecord", null)
                        .WithOne()
                        .HasForeignKey("Chido.Data.Entities.SkillMotionEffectMasterRecord", "SkillKey", "MotionIndex", "MotionType")
                        .HasPrincipalKey("Chido.Data.Entities.SkillMotionMasterRecord", "SkillKey", "MotionIndex", "MotionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Chido.Data.Entities.SkillMotionHealMasterRecord", b =>
                {
                    b.HasOne("Chido.Data.Entities.SkillMotionMasterRecord", null)
                        .WithOne()
                        .HasForeignKey("Chido.Data.Entities.SkillMotionHealMasterRecord", "SkillKey", "MotionIndex", "MotionType")
                        .HasPrincipalKey("Chido.Data.Entities.SkillMotionMasterRecord", "SkillKey", "MotionIndex", "MotionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
